/// Build script for usermode-desktop.
///
/// At build time (host-only), this script:
///   1. Reads Inter-Regular.ttf and Inter-SemiBold.ttf from assets/
///   2. Uses fontdue to rasterize glyphs for printable ASCII (32–126) at two sizes
///   3. Writes src/atlas_data.rs — a statically embedded glyph atlas (no runtime dep)
///
/// The atlas layout (per size/weight):
///   - Each glyph is stored as a CELL_W × CELL_H array of u8 coverage values (0=transparent, 255=opaque)
///   - Glyphs are indexed by ASCII code (32..=126), index = ch as usize - 32
///   - Metrics: advance_x (how many pixels to move pen forward) per glyph
///
use std::io::Write;
use std::path::PathBuf;

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_dir  = std::env::var("OUT_DIR").unwrap();

    // Tell linker where to find linker.ld, resolving any potential path/symlink mismatches (e.g., AE Rustanium vs Rustix OS)
    let mut manifest_path = std::path::PathBuf::from(&manifest);
    if !manifest_path.join("linker.ld").exists() {
        let manifest_str = manifest.replace("AE Rustanium", "Rustix OS");
        let alt_path = std::path::PathBuf::from(&manifest_str);
        if alt_path.join("linker.ld").exists() {
            manifest_path = alt_path;
        } else if let Ok(cwd) = std::env::current_dir() {
            if cwd.join("linker.ld").exists() {
                manifest_path = cwd;
            } else {
                let cwd_str = cwd.to_string_lossy().replace("AE Rustanium", "Rustix OS");
                let alt_cwd = std::path::PathBuf::from(&cwd_str);
                if alt_cwd.join("linker.ld").exists() {
                    manifest_path = alt_cwd;
                }
            }
        }
    }

    println!("cargo:rustc-link-search={}", manifest_path.display());
    println!("cargo:rerun-if-changed={}", manifest_path.join("linker.ld").display());
    println!("cargo:rerun-if-changed={}", manifest_path.join("assets/Inter-Regular.ttf").display());
    println!("cargo:rerun-if-changed={}", manifest_path.join("assets/Inter-SemiBold.ttf").display());

    // ── Rasterize ──────────────────────────────────────────────────────────
    let regular_bytes  = std::fs::read(manifest_path.join("assets/Inter-Regular.ttf")).expect("Inter-Regular.ttf not found");
    let semibold_bytes = std::fs::read(manifest_path.join("assets/Inter-SemiBold.ttf")).expect("Inter-SemiBold.ttf not found");

    // We produce two sizes: SMALL (body text) and LARGE (titles/headings)
    let sizes: &[(u32, f32, &str)] = &[
        (14, 14.0, "S"),   // 14px body text
        (18, 18.0, "M"),   // 18px medium
        (24, 24.0, "L"),   // 24px large / titles
    ];

    let fonts = [
        ("REGULAR",  &regular_bytes[..]),
        ("SEMIBOLD", &semibold_bytes[..]),
    ];

    let ascii_start: usize = 32;
    let ascii_end:   usize = 127;
    let num_glyphs        = ascii_end - ascii_start;

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by build.rs — DO NOT EDIT\n");
    out.push_str("// Inter font rasterized glyph atlas.\n");
    out.push_str("// Coverage values: 0 = transparent, 255 = fully opaque.\n\n");

    for (weight_name, font_bytes) in &fonts {
        let font_settings = fontdue::FontSettings { scale: 40.0, ..Default::default() };
        let font = fontdue::Font::from_bytes(*font_bytes, font_settings)
            .expect("Failed to parse Inter font");

        for &(cell_h, px_size, size_suffix) in sizes {
            // Determine max advance width across all glyphs to set CELL_W
            let mut max_advance: i32 = 0;
            for ch in (ascii_start as u8)..(ascii_end as u8) {
                let (metrics, _) = font.rasterize(ch as char, px_size);
                let adv = metrics.advance_width.ceil() as i32;
                if adv > max_advance { max_advance = adv; }
            }
            let cell_w = (max_advance + 2) as usize;

            // Glyph pixel data: [num_glyphs][cell_h][cell_w]
            let mut pixels: Vec<Vec<Vec<u8>>> = Vec::new();
            let mut advances: Vec<u8> = Vec::new();
            let mut offsets_x: Vec<i8> = Vec::new();
            let mut offsets_y: Vec<i8> = Vec::new();

            for ch in (ascii_start as u8)..(ascii_end as u8) {
                let (metrics, bitmap) = font.rasterize(ch as char, px_size);
                advances.push(metrics.advance_width.ceil() as u8);
                offsets_x.push(metrics.xmin as i8);
                // fontdue's ymin is from baseline upward; we need top-down
                // baseline_y = cell_h - 2 (small descender gap)
                let baseline = cell_h as i32 - 3;
                let top_offset = baseline - (metrics.height as i32 + metrics.ymin as i32);
                offsets_y.push(top_offset.clamp(-127, 127) as i8);

                let mut glyph = vec![vec![0u8; cell_w]; cell_h as usize];
                for row in 0..metrics.height {
                    for col in 0..metrics.width {
                        let src_idx = row * metrics.width + col;
                        let dst_row = top_offset + row as i32;
                        let dst_col = metrics.xmin + col as i32;
                        if dst_row >= 0 && dst_row < cell_h as i32
                           && dst_col >= 0 && dst_col < cell_w as i32 {
                            glyph[dst_row as usize][dst_col as usize] = bitmap[src_idx];
                        }
                    }
                }
                pixels.push(glyph);
            }

            // Emit constants
            let const_prefix = format!("ATLAS_{weight_name}_{size_suffix}");
            let ch_usize = cell_h as usize;

            out.push_str(&format!("pub const {const_prefix}_CELL_W: usize = {cell_w};\n"));
            out.push_str(&format!("pub const {const_prefix}_CELL_H: usize = {ch_usize};\n"));
            out.push_str(&format!("pub const {const_prefix}_N: usize = {num_glyphs};\n"));

            // Advance widths
            out.push_str(&format!("pub static {const_prefix}_ADV: [u8; {num_glyphs}] = ["));
            for a in &advances { out.push_str(&format!("{a},")); }
            out.push_str("];\n");

            // X offsets
            out.push_str(&format!("pub static {const_prefix}_OX: [i8; {num_glyphs}] = ["));
            for o in &offsets_x { out.push_str(&format!("{o},")); }
            out.push_str("];\n");

            // Y offsets (stored but used implicitly via pre-placed cells)
            out.push_str(&format!("pub static {const_prefix}_OY: [i8; {num_glyphs}] = ["));
            for o in &offsets_y { out.push_str(&format!("{o},")); }
            out.push_str("];\n");

            // Pixel data — flat: [glyph_idx][row][col]
            out.push_str(&format!(
                "pub static {const_prefix}_PIXELS: [[[u8; {cell_w}]; {ch_usize}]; {num_glyphs}] = [\n"
            ));
            for glyph in &pixels {
                out.push_str("    [\n");
                for row in glyph {
                    out.push_str("        [");
                    for &px in row { out.push_str(&format!("{px},")); }
                    out.push_str("],\n");
                }
                out.push_str("    ],\n");
            }
            out.push_str("];\n\n");
        }
    }

    let dst = PathBuf::from(&out_dir).join("atlas_data.rs");
    let mut f = std::fs::File::create(&dst).unwrap();
    f.write_all(out.as_bytes()).unwrap();

    println!("cargo:warning=Inter font atlas generated → {}", dst.display());
}
